### ISSUE TITLE
Kaiwa Error Logs 

### ISSUE THREAD

**Issue by Akkkarian** [digicoop/kaiwa#29]
I Just set up kaiwa with a connect to our own ldap and XMPP Server but i can't log in to kaiwa wehre can i find error logs to fix that problem?

**Comment by xtavras** [comment]
Same thing, running prosody 0.10 with configs from kaiwa-server repo, everything works fine with jabber client (pidgin), websockets are available too ("It works! Now point your WebSocket client to this URL to connect to Prosody." message if opened in browser), but kaiwa client is stuck at "Connecting". 
Any way to see what's going on? I've heard about node-inspector but it seems too hardcode for me.

**Comment by pwe123345** [comment]
Do you have any solutions for that?

I think Im having trouble, configuring kaiwa-client. Can someone help me please?

**Comment by manwe-pl** [comment]
Did you edit dev_config.json and fill values like server.wss?

**Comment by pwe123345** [comment]
Hello,

thank you for your answer, but I already replaced kaiwa.



Mit freundlichem Gruß/Kind regards 
i. A. Philipp Wehling 
_____________________________________________ 
Systemadministrator
megatel Informations- und Kommunikationssysteme GmbH 
Ein Unternehmen der OHB SE 
Lise-Meitner-Str. 2 * 28359 Bremen 
Tel.: 04 21/2 20 95-0 * Fax: 04 21/2 20 95-16 
Amtsgericht Bremen HRB 12489 
Geschäftsführer: 
Jörg Biesewig 

----- Ursprüngliche Mail -----
Von: "manwe" <notifications@github.com>
An: "digicoop/kaiwa" <kaiwa@noreply.github.com>
CC: "pwe123345" <philipp.wehling@megatel.de>
Gesendet: Sonntag, 21. Juni 2015 20:08:32
Betreff: Re: [kaiwa] Kaiwa Error Logs  (#29)



Did you edit dev_config.json and fill values like server.wss?

**Comment by manwe-pl** [comment]
Out of curiosity - with what? Anything with XEP-0313 support?

**Comment by pwe123345** [comment]
Hello,

I dont know exactly, if its implemented. But I changed to jappix.

Good luck with that ;)


Mit freundlichem Gruß/Kind regards 
i. A. Philipp Wehling 
_____________________________________________ 
Systemadministrator
megatel Informations- und Kommunikationssysteme GmbH 
Ein Unternehmen der OHB SE 
Lise-Meitner-Str. 2 * 28359 Bremen 
Tel.: 04 21/2 20 95-0 * Fax: 04 21/2 20 95-16 
Amtsgericht Bremen HRB 12489 
Geschäftsführer: 
Jörg Biesewig 

----- Ursprüngliche Mail -----
Von: "manwe" <notifications@github.com>
An: "digicoop/kaiwa" <kaiwa@noreply.github.com>
CC: "pwe123345" <philipp.wehling@megatel.de>
Gesendet: Montag, 22. Juni 2015 19:38:08
Betreff: Re: [kaiwa] Kaiwa Error Logs  (#29)



Out of curiosity - with what? Anything with XEP-0313 support?

**Comment by sammcj** [comment]
Where are errors logged to? They don't even seem to go to stdout?

**Comment by DN0000** [comment]
Not being familiar with node apps - I'd also appreciate being able to get some logs. Currently trying to connect to a Cisco IM&P service with BOSH and not having too much luck!

**Comment by gfriloux** [comment]
Hello, i am actually the same problem than issue creator.

I cant log using kaiwa to my prosody xmpp server.
websocket is enabled, seems working (see http://friloux.me:5280/xmpp-websocket ).
I can connect to my xmpp server using pidgin or converse.js.
Although, kaiwa fails. in the console of my browser i do get : 
WebSocket connection to 'wss://friloux.me:5280/xmpp-websocket/' failed: Error in connection establishment: net::ERR_TIMED_OUT

We is weird since my browser can access, pidgin can, converse can, netcat can (both from outside than in localhost), so i am out of ideas.

So, where are the log, so we can try to look at the problem ? :)

**Comment by gfriloux** [comment]
So, i ended up to understand that 5280 is http and 5281 is https, an thus, i was telling kaiwa to do https on the http service, which explains the timeout.

So, i moved to port 5281, restarted kaiwa, and now i no more get a timeout error in the browser's console, i only get sent back to login page without any message.

How to dig into kaiwa to know whats going on ?

**Comment by gfriloux** [comment]
So, i found issue #9 and also found this issue from stanza.io : https://github.com/otalk/stanza.io/issues/25
I had the invalid-xml log in prosody's log, was using 0.9.8 (archlinux).
Upgraded to 0.10 using AUR (prosody-hg) and i have been able to login.

I came to the settings page, with this error that comes up to my browser's console : 
```
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (https://chat.friloux.me/app.e6699e2d.min.js:14:21438)
    at n._rejectCallback (https://chat.friloux.me/app.e6699e2d.min.js:13:23041)
    at n._settlePromiseFromHandler (https://chat.friloux.me/app.e6699e2d.min.js:13:23689)
    at n._settlePromiseAt (https://chat.friloux.me/app.e6699e2d.min.js:13:24861)
    at n._settlePromises (https://chat.friloux.me/app.e6699e2d.min.js:13:26726)
    at i._drainQueue (https://chat.friloux.me/app.e6699e2d.min.js:12:20727)
    at i._drainQueues (https://chat.friloux.me/app.e6699e2d.min.js:12:20788)
    at drainQueues (https://chat.friloux.me/app.e6699e2d.min.js:12:19000)
```

If anyone can tell me if this is of interest and needs a separate issue to be opened.

**Comment by gfriloux** [comment]
Well, as this project doesnt seems really active since months, i think i better end up here.

**Comment by mwild1** [comment]
@gfriloux Could you do everyone a favour and open a new bug report for that error? Just so it doesn't get lost at the end of the comments on this unrelated issue. Thanks! :)

**Comment by r4g3128** [comment]
set up apache as proxy, enable bosh and bosh-features and everything will be fine:
`   

        <IfModule mod_proxy.c>

                <IfModule mod_proxy_http.c>

                        ProxyRequests Off

                        ProxyPass /http-bind http://localhost:5280/http-bind/

                        ProxyPassReverse /http-bind http://localhost:5280/http-bind/

                </IfModule>

        </IfModule>
`

prosody.cfg.lua
`

    cross_domain_bosh = true; 

    consider_bosh_secure = true;
`

now kaiwa can connect to your prosody at http://yourserver/http-bind/
