### ISSUE TITLE
Kaiwa npm install fails

### ISSUE THREAD

**Issue by gburgwardt** [digicoop/kaiwa#45]
Hello

With a fully up to date npm, kaiwa fails with the following error-
```
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-042stab108.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/garrett/kaiwa/node_modules/LDAP
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Linux 2.6.32-042stab108.2
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.1.0
npm ERR! code ELIFECYCLE

npm ERR! LDAP@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the LDAP@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the LDAP package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls LDAP
npm ERR! There is likely additional logging output above.
```

I tried installing openldap as suggested on here, but it failed in the same way. Link to the fail log-

http://pastebin.com/raw.php?i=mq2G5nse

I would really like to try out kaiwa as it looks great, so any advice would be appreciated.

**Comment by gburgwardt** [comment]
Figured it out, run the following script to install kaiwa-

#!/bin/bash
sudo apt-get install git libldap2-dev uuid-dev nodejs nodejs-legacy npm -y
cd ~
git clone https://github.com/digicoop/kaiwa.git
cd kaiwa
npm install
node server

**Comment by andersruneson** [comment]
Could you send in a pull request for to update the readme with the packages needed?
