### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by robn** [digicoop/kaiwa#52]
Build fails for me. New Debian 7.9 install, nodejs 0.12.7 from NodeSource, kaiwa @4a48e16. Following instructions from README.

```
root@qext3:~# git clone https://github.com/digicoop/kaiwa.git
Cloning into 'kaiwa'...
remote: Counting objects: 4171, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 4171 (delta 11), reused 0 (delta 0), pack-reused 4140
Receiving objects: 100% (4171/4171), 2.50 MiB | 1.02 MiB/s, done.
Resolving deltas: 100% (2607/2607), done.
root@qext3:~# cd kaiwa/
root@qext3:~/kaiwa# npm install
npm WARN peerDependencies The peer dependency jshint@ included from precommit-hook will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> precommit-hook@1.0.7 install /root/kaiwa/node_modules/precommit-hook
> hook_install

Creating .git/hooks/pre-commit...
 
> dtrace-provider@0.2.8 install /root/kaiwa/node_modules/ldapjs/node_modules/dtrace-provider
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:366:17)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/kaiwa/node_modules/ldapjs/node_modules/dtrace-provider
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing dtrace-provider@0.2.8
 
> node-stringprep@0.7.2 install /root/kaiwa/node_modules/stanza.io/node_modules/xmpp-jid/node_modules/node-stringprep
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:366:17)
ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/kaiwa/node_modules/stanza.io/node_modules/xmpp-jid/node_modules/node-stringprep
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN prefer global jshint@2.8.0 should be installed with -g
-
> iconv@2.1.10 install /root/kaiwa/node_modules/jxt/node_modules/ltx/node_modules/node-expat/node_modules/iconv
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._handle.onerror (zlib.js:366:17)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/kaiwa/node_modules/jxt/node_modules/ltx/node_modules/node-expat/node_modules/iconv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/kaiwa/npm-debug.log
```

I'm a competent sysadmin, but I don't know much about nodejs, so I haven't made any attempt to debug anything yet.

**Comment by robn** [comment]
I finally got it sorted. There seems to be two parts. One is dependencies: installing `g++` brought in everything I needed. The other was user - apparently node (or maybe npm) isn't thrilled about running as root (I have my reasons). `npm config set user 0` and `npm config set unsafe-perl true` got me there.

You don't have to document the user stuff I guess; running as root isn't quite standard. But getting the dependency list correct is crucial.
