### ISSUE TITLE
Unable to start chat

### ISSUE THREAD

**Issue by fischerman** [digicoop/kaiwa#80]
I'm using Kaiwa with ejabberd and no LDAP. I'm able to log in and can see my rosters. However I'm not able to select a roster to chat with. The settings btn also doesn't do anything.
I get the following log in the console (Google Chrome)
```
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at module.exports.HumanModel.define.derived.displayName.fn (http://10.1.1.97/app.nonCached.js:5084:28)
    at _.extend._getDerivedProperty (http://10.1.1.97/app.nonCached.js:33355:63)
    at Object.defineProperty.get (http://10.1.1.97/app.nonCached.js:32626:21)
    at anonymous (http://10.1.1.97/app.nonCached.js:7533:306)
    at Backbone.View.extend.renderWithTemplate (http://10.1.1.97/app.nonCached.js:34835:52)
    at Backbone.View.extend.renderAndBind (http://10.1.1.97/app.nonCached.js:34802:12)
    at module.exports.HumanView.extend.render (http://10.1.1.97/app.nonCached.js:8349:14)
    at addView (http://10.1.1.97/app.nonCached.js:34937:18)
    at triggerEvents (http://10.1.1.97/app.nonCached.js:9982:57)
    at Backbone.Events.trigger (http://10.1.1.97/app.nonCached.js:9922:19)
    at _.extend._onModelEvent (http://10.1.1.97/app.nonCached.js:10709:20)
    at triggerEvents (http://10.1.1.97/app.nonCached.js:9983:58)
    at Backbone.Events.trigger (http://10.1.1.97/app.nonCached.js:9923:22)
    at _.extend.set (http://10.1.1.97/app.nonCached.js:10502:28)
    at _.extend.add (http://10.1.1.97/app.nonCached.js:10411:19)
    at module.exports.BaseCollection.extend.update (http://10.1.1.97/app.nonCached.js:5476:26)
```

**Comment by calbrecht** [comment]
That happens when this.name is not set in https://github.com/digicoop/kaiwa/blob/384c4f063a53e7fd4f6c507602b010127431577b/clientapp/models/muc.js#L47
